[package]
name = "teensy3-rs-demo"
version = "0.1.0"
authors = ["Joakim Ohlrogge <joakim.ohlrogge@agical.se>"]

[dependencies]
teensy3 = "0.1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
